### PR TITLE
adapt some logic on linux

### PR DESCRIPTION
**Pull request by jerry4718**
- adapt find app on linux
- compat show icon on linux (sync implement)

### CODE REVIEW

**Comment by jerry4718** [comment]
Some logic reference here [Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html)
I have only tested it on my deepin Linux, and it is reasonable to use it

**Comment by jerry4718** [comment]
I think the problem of  ```can not find module 'simple-plist'``` can be solved completely in this way
[Change the import of adapter to dynamic import](https://github.com/pd4d10/debugtron/pull/19/commits/e9393f30b5693b77a330a6dfaf47aa7ecdb11261)

Because ```simple-plist``` should not be directly imported when it is released to win or linux. It is not useful for win or linux because it is a module that only implements some functions for mac os.

If ```electron-forge``` has the ability of conditional compilation, I think ```adapter``` should be handled in that way.

**Comment by pd4d10** [comment]
Sorry for the late reply.

There seems to be a lot of conflict since the lastet `main` branch has significant changes. Could you please run a rebase? Then we can merge this PR

> the problem of `can not find module 'simple-plist'`

I'm not sure if this issue still exists. If yes then fixes are very welcome

Thanks!

**Comment by jerry4718** [comment]
> Sorry for the late reply.
> 
> There seems to be a lot of conflict since the lastet `main` branch has significant changes. Could you please run a rebase? Then we can merge this PR
> 
> > the problem of `can not find module 'simple-plist'`
> 
> I'm not sure if this issue still exists. If yes then fixes are very welcome
> 
> Thanks!

okay, let me see

**Comment by jerry4718** [comment]
> There seems to be a lot of conflict since the lastet `main` branch has significant changes. Could you please run a rebase? Then we can merge this PR

I am not very proficient in rebase, so I created a new PR ( #35 )

**Pull request closed without merging**
